### ISSUE TITLE
[checkMK] Monitor disk read-only state

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#2471]
Something like:

```
datadog_typed_checks:
  - type: disk
    configuration:
      init_config:
      instances:
        use_mount: false
        service_check_rw: true
        tags:
          - 'disk_service:figgy'
```

reference:
- https://docs.datadoghq.com/integrations/disk/
- https://github.com/DataDog/integrations-core/blob/master/disk/datadog_checks/disk/data/conf.yaml.default
