### ISSUE TITLE
Make Ansible alerts more specific

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#2852]
Some ideas for making alerts from Ansible playbook runs even more useful:
- make the Slack alert a shared tasks file
- make the Slack channel a variable so playbooks can choose specific channels
- include the play name in the alert

Sample code:
```
    - name: tell everyone on slack you ran an ansible playbook
      slack:
        token: "{{ vault_pul_slack_token }}"
        msg: Ansible ran `{{ ansible_play_name }}` on {{ inventory_hostname }}
        channel: #server-alerts
```
