### ISSUE TITLE
Ensure ruby_s uninstalls unwanted packages

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#3491]
The ruby_s role has been inconsistent in uninstalling older versions of Ruby. 

When trying to imitate the ruby_s ruby cleanup step for the PHP role, @maxkadel and @acozine found that using a wildcard was more effective than creating a list from apt. 

See https://github.com/pulibrary/princeton_ansible/pull/3490/files and [Ansible documentation](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#parameter-name)

```yaml
- name: php | remove packages that begin with 'php{{ php_unwanted_version }}'
  ansible.builtin.apt:
    name: php{{ php_unwanted_version }}*
    state: absent
    autoremove: true
  notify: restart apache
```
