### ISSUE TITLE
Cannot run tigerdata playbook on Production

### ISSUE THREAD

**Issue by JaymeeH** [pulibrary/princeton_ansible#5038]
### What maintenance needs to be done?
Tigerdata playbook can run on staging and qa, but not production. 

error message when attempting to run the playbook on production:

TASK [Ensure the presence of nfs mount] ************************************************************************************************
fatal: [tigerdata-prod2.princeton.edu]: FAILED! => {"changed": false, "msg": "Error mounting /mnt/nfs/tigerdata: mount.nfs: access denied by server while mounting 128.112.204.89:/var/nfs/tigerdata\n"}
fatal: [tigerdata-prod1.princeton.edu]: FAILED! => {"changed": false, "msg": "Error mounting /mnt/nfs/tigerdata: mount.nfs: access denied by server while mounting 128.112.204.89:/var/nfs/tigerdata\n"}

Affected lines:
```
  - share: "{{ tigerdata_fileshare_mount }}"
    hosts:
      - name: "{{ pdc_describe_prod1 }}"
        options:
          - rw
          - sync
          - no_subtree_check
          - no_root_squash
          - no_wdelay
      - name: "{{ pdc_describe_prod2 }}"
        options:
          - rw
          - sync
          - no_subtree_check
          - no_root_squash
          - no_wdelay
```

### Level of urgency
- [ ] High
- [ x ] Moderate
- [ ] Low

### EOL upgrade
- [ ] EOL Date MM/DD/YYYY

### Why is this maintenance needed?
- A clear description of why this is needed.

### Acceptance criteria
 - [ ] NFS fileshare for tigerdata production needs to mounted to tigerdata instead of pdc
 - [ ] The playbook should run on production without errors
