### ISSUE TITLE
[video_reserves] Running the playbook does not enable the php module in apache2

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#5457]
### Expected behavior
Running the video_reserves playbook results in a playable video at https://videoreserves-staging.princeton.edu/hrc/vod/clip.php or https://videoreserves-prod.princeton.edu/hrc/vod/clip.php 

![image](https://github.com/user-attachments/assets/bd84a42b-8f41-4c1c-b8f4-42b4bbc66948)

### Actual behavior
Displays the php code for the video player, not the video player itself
![image](https://github.com/user-attachments/assets/1848f9cf-519c-42e7-9dcb-870e633f33aa)

### Steps to replicate
I believe if you disable the php8.3 module you will see this happen `sudo a2dismod php8.3` and restart apache. We were able to fix this on production by running `sudo a2enmod php8.3` manually, but this is not in the playbook.

### Impact of this bug
We cannot reliably run the video reserves playbook.

### Implementation notes, if any
As of 10/23/2024 this was manually fixed on production, but left in a broken state on staging to allow for testing.

Tried adding the following to the video_reserves role, but it did not fix the issue:

```yaml
- name: video_reserves | install apache modules
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  notify: restart apache
  with_items:
    - php{{ php_version }}
```
