### ISSUE TITLE
Optimize CI for concurrent builds

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#627]
By default, CircleCI only permits a low threshold for concurrent builds (please see https://circleci.com/docs/2.0/parallelism-faster-jobs/ and https://circleci.com/pricing/).  These test suites could be organized to run tests for more than one Role for optimizing the limited number of concurrent builds we have available.

**Comment by jrgriffiniii** [comment]
Using shell scripting doesn't appear to work with this approach (most of the features needed are only available in the BASH - CircleCI does not offer this):

```sh
#!/bin/sh -eo pipefail
PULIBRARY_ROLES=$( `find . -type d -regex '.*/roles/pulibrary.*/molecule/.*' | awk 'BEGIN { FS="/"; } { print $3 }' | uniq` )
CURRENT_PULIBRARY_ROLE=1
CURRENT_PULIBRARY_ROLES=${PULIBRARY_ROLES[@]:$CURRENT_PULIBRARY_ROLE:2}
/bin/sh: pulibrary.pas_code: not found
Exited with code 127
```

(which was built from https://github.com/pulibrary/princeton_ansible/commit/10c85700f1c06e120d448fc6f05186f6cafa651e)

**Comment by jrgriffiniii** [comment]
Trying to restructure the parallelization of test executions using a Python script is proving to be more problematic, and I'm not quite certain how to proceed, as the following error is triggered with an experimental approach:

```
#!/bin/sh -eo pipefail
python ./test.py
Executing the tests for roles/pulibrary.nginxplus
Traceback (most recent call last):
  File "./test.py", line 29, in <module>
    test_process = subprocess.run(['molecule', 'test'], stdout=subprocess.STDOUT)
  File "/usr/local/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 9] Bad file descriptor
Exited with code 1
```

https://github.com/pulibrary/princeton_ansible/compare/master...jrgriffiniii:issues-627-jrgriffiniii-circleci-concurrent-builds

**Comment by jrgriffiniii** [comment]
Looking at the documentation for GitLab CI, I'm not certain that this approach can be undertaken without addressing the following:
> Tip: Parallelize tests suites across parallel jobs. Different languages have different tools to facilitate this.

(https://docs.gitlab.com/ee/ci/yaml/#parallel)

https://pypi.org/project/pytest-xdist/ provides parallelization for Python test suites, and https://github.com/pycontribs/pytest-molecule/blob/master/pytest_molecule/__init__.py#L157 might provide a way to integrate Molecule test suites for Roles with `pytest`

**Comment by jrgriffiniii** [comment]
`MOLECULE_INVENTORY_FILE` does not seem to be set when these tests are run using `pytest`:
```
E   KeyError: 'MOLECULE_INVENTORY_FILE'
________ ERROR collecting roles/pulibrary.tomcat8/molecule/default/tests/test_tomcat8.py _________
roles/pulibrary.tomcat8/molecule/default/tests/test_tomcat8.py:7: in <module>
    os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')
../../../../.local/share/virtualenvs/princeton_ansible-gphETEdW/lib/python3.7/os.py:678: in __getitem__
    raise KeyError(key) from None
E   KeyError: 'MOLECULE_INVENTORY_FILE'
```

**Comment by jrgriffiniii** [comment]
It appears to be the case that the `testinfra` integration for `Ansible` on https://github.com/pulibrary/princeton_ansible/blob/master/roles/pulibrary.ruby/molecule/default/tests/test_ruby.py#L6 *must* remain in the global scope.  I was able to get the Docker environment provisioned successfully, but the following pattern simply will *not* work:

```python
import os
import testinfra.utils.ansible_runner
import unittest


class Apache2TestCase(unittest.TestCase):
    def setUp(self):
        self.testinfra_hosts = testinfra.utils.ansible_runner.AnsibleRunner(
                os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')

    def test_is_apache_installed(self, host):
        pkg = host.package('apache2')

        assert pkg.is_installed

    def test_apache_listening_http(self, host):
        socket = host.socket('tcp://0.0.0.0:80')

        assert socket.is_listening
```

**Comment by jrgriffiniii** [comment]
I'm very sorry, I'm now becoming skeptical that `pytest` can at all be used to integrate with Molecule using the approach which is currently undertaken.  During executing, the following Ansible inventory is generated in a role-specific directory: `~/.cache/molecule/pulibrary.apache2/default/inventory/ansible_inventory.yml`:

```yaml
# Molecule managed

---
all:
  hosts:
    instance: &id001
      ansible_connection: docker
  vars:
    molecule_ephemeral_directory: '{{ lookup(''env'', ''MOLECULE_EPHEMERAL_DIRECTORY'')
      }}'
    molecule_file: '{{ lookup(''env'', ''MOLECULE_FILE'') }}'
    molecule_instance_config: '{{ lookup(''env'', ''MOLECULE_INSTANCE_CONFIG'') }}'
    molecule_no_log: '{{ lookup(''env'', ''MOLECULE_NO_LOG'') or not molecule_yml.provisioner.log|default(False)
      | bool }}'
    molecule_scenario_directory: '{{ lookup(''env'', ''MOLECULE_SCENARIO_DIRECTORY'')
      }}'
    molecule_yml: '{{ lookup(''file'', molecule_file) | molecule_from_yaml }}'
ungrouped:
  hosts:
    instance: *id001
  vars: {}
```

Running `pytest` alone does not seem to regenerate these, so I'm concerned that avoiding the usage of `molecule test` without abandoning `testinfra` might not be possible.
