### ISSUE TITLE
[prancible] security playbook fails on some machines for CrowdStrike public key

### ISSUE THREAD

**Issue by VickieKarasic** [pulibrary/princeton_ansible#6276]
### Expected behavior
`security_theater` playbook should update or skip machines each week 

### Actual behavior
The following machines are failing: 

Staging: 

- [x] catalog-staging1.princeton.edu
- [x] catalog-staging2.princeton.edu
- [x] dpul-collections-staging1.lib.princeton.edu
- [x] dpul-collections-staging2.lib.princeton.edu
- [x] figgy-web-staging1.princeton.edu
- [x] figgy-web-staging2.princeton.edu
- [x] lib-sftp-staging1.princeton.edu
- [x] mflux-staging1.lib.princeton.edu
- [x] nomad-client-staging1.lib.princeton.edu
- [x] nomad-client-staging2.lib.princeton.edu
- [x] nomad-client-staging3.lib.princeton.edu
- [x] orcid-staging1.princeton.edu
- [x] sandbox-acozine.lib.princeton.edu
- [x] sandbox-fkayiwa1.lib.princeton.edu
- [x] sandbox-pp9425.lib.princeton.edu
- [x] sandbox-vkarasic.lib.princeton.edu

QA: 
- [x] mflux-qa1.lib.princeton.edu

Prod: 
- [x] ansible-exec-node1.princeton.edu
- [x] ansible-exec-node2.princeton.edu
- [x] ansible-tower1.princeton.edu
- [x] ansible-tower2.princeton.edu
- [x] lib-postgres-prod3.princeton.edu
- [x] lib-sftp-prod1.princeton.edu
- [x] mflux-prod1.lib.princeton.edu 
- [x] nomad-client-prod1.lib.princeton.edu
- [x] nomad-client-prod2.lib.princeton.edu
- [x] nomad-client-prod3.lib.princeton.edu
- [x] nomad-client-prod4.lib.princeton.edu

### Error messages

`Failed to validate GPG signature for falcon-sensor-7.24.0-17706.el9.x86_64: Public key for falcon-sensor-7.24.0-17706.el9.x86_64.rpm is not installed` 

### Steps to replicate
Run `security_theater` playbook on Tower on prod and qa envs 

### Impact of this bug
Machines are not getting security updates 

### Relevant links and code snippets, if applicable

```
```

**Comment by VickieKarasic** [comment]
I've reached out to OIT to ask how best to retrieve a new GPG key.

**Comment by acozine** [comment]
I got the new GPG key from OIT - check Slack for it.

**Comment by VickieKarasic** [comment]
We realized that we can do this manually on the machines that fail -- so far have tried this on RedHat machines that have checkmarks in the above list and the manual method has worked. The question is whether we want to keep trying to fix this at the playbook level, since it also looks like Linux machines are involved. Started a draft PR to address this: [6359](https://github.com/pulibrary/princeton_ansible/pull/6359).

**Comment by VickieKarasic** [comment]
Tried to import this manually on an Ubuntu machine (`orcid-staging1`) using `gpg --import <file_name.gpg>` which looked to be successful on the machine itself, but the playbook failed on Tower with this error: 
`
fatal: [orcid-staging1.princeton.edu]: FAILED! => {"after": ["561F9B9CAC40B2F7", "CF693C004DB76CB6", "7FCC7D46ACCC4CF8", "1646B01B86E50310", "02820C39D50AF136", "23E7166788B63E1E", "4F77679369475BAA", "D94AA3F0EFE21092", "871920D1991BC93C"], "before": ["561F9B9CAC40B2F7", "CF693C004DB76CB6", "7FCC7D46ACCC4CF8", "1646B01B86E50310", "02820C39D50AF136", "23E7166788B63E1E", "4F77679369475BAA", "D94AA3F0EFE21092", "871920D1991BC93C"], "changed": false, "fp": "2E9ABB6578F12340", "id": "2E9ABB6578F12340", "key_id": "2E9ABB6578F12340", "msg": "apt-key did not return an error, but failed to add the key (check that the id is correct and *not* a subkey)", "short_id": "78F12340"}`

Tower output: [https://ansible-tower.princeton.edu/#/jobs/playbook/24582/output](https://ansible-tower.princeton.edu/#/jobs/playbook/24582/output)

**Comment by kayiwa** [comment]
Try this? https://github.com/CrowdStrike/ansible_collection_falcon/issues/594

**Comment by VickieKarasic** [comment]
I tried adding the suggestion `falcon_gpg_key_check: false` in the link above but not sure if I added it to the correct place/in the correct task: 

```
  - name: include falcon_install
    ansible.builtin.include_role:
      name: crowdstrike.falcon.falcon_install
    vars:
      falcon_client_id: "{{ vault_crowdstrike_client_id }}"
      falcon_client_secret: "{{ vault_crowdstrike_secret }}"
      falcon_sensor_version_decrement: 2
      **falcon_gpg_key_check: false**
      # be sure to add this so we don't download if we don't need to
      falcon_api_sensor_download_path: /opt/
    when:
      - "'falcon-sensor' not in ansible_facts.services"
```

When I run security_theater, I now get this error with that line inserted: 
```

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Authenticate to CrowdStrike API] ************************************
fatal: [catalog-staging1.princeton.edu -> localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
```
